services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        WWWUSER: '${WWWUSER}'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      PHP_IDE_CONFIG: 'serverName=laravel.test'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:14.13'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailpgsql:
    driver: local
